name: Build RSS (piotrkow.pl)

on:
  workflow_dispatch:
  schedule:
    # co godzinę
    - cron: "0 * * * *"

concurrency:
  group: build-rss-piotrkow
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          python scraper.py

      - name: Show feed head
        run: |
          head -n 40 feed.xml || true

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Pull (rebase) in case of concurrent pushes
        run: |
          git pull --rebase origin ${{ github.ref_name }} || true

      - name: Commit feed
        run: |
          git add feed.xml
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update feed.xml [skip ci]"
          fi

      - name: Push
        run: |
          git push origin HEAD:${{ github.ref_name }} || true
